---

- hosts: localhost
  become: yes
  tasks:

    - name: Install general apps
      pacman:
        name:
          - ansible
          - git
          - yay # to install aur packages later

          # general apps
          - firefox
          - torbrowser-launcher
          - gimp
          - vlc
          - audacious
          - deluge-gtk
          - galculator
          - signal-desktop
          - libreoffice-fresh

    - name: Install utils
      pacman:
        name:
          - catfish # file search
          - 7zip
          - ffmpeg
          - ripgrep
          - entr
          - zbar
          - xclip
          - jq
          - htop
          - curl

    - name: Install programming stuff
      pacman:
        name:
          - cmake
          - gcc
          - clang
          - gdb

          - go

          - dotnet-sdk

          - python

          - nodejs
          - npm

          - sqlite
          - sqlitebrowser

          - wireshark-qt

          - docker
          - docker-compose

    - name: Install IDEs
      pacman:
        name:
          - neovim
          - neovim-qt
          - code
          - qtcreator

    # @MarkFix shenanigans required to install AUR packages...
    #- name: Install AUR packages with yay
    #  become: no
    #  shell: yay -S --noconfirm google-chrome etcher-bin

    - name: Set bash/nvim/vscode/idea config
      become: no
      shell: |
        [ -L ~/.bashrc ] && rm ~/.bashrc
        [ -f ~/.bashrc ] && mv ~/.bashrc ~/.bashrc$(date +%Y%m%d)
        ln -s $(pwd)/bash/.bashrc ~/.bashrc

        [ -L ~/.inputrc ] && rm ~/.inputrc
        [ -f ~/.inputrc ] && mv ~/.inputrc ~/.inputrc$(date +%Y%m%d)
        ln -s $(pwd)/bash/.inputrc ~/.inputrc

        [ -L ~/.xprofile ] && rm ~/.xprofile
        [ -f ~/.xprofile ] && mv ~/.xprofile ~/.xprofile$(date +%Y%m%d)
        ln -s $(pwd)/bash/.xprofile ~/.xprofile

        [ -L ~/.gitconfig ] && rm ~/.gitconfig
        [ -f ~/.gitconfig ] && mv ~/.gitconfig ~/.gitconfig$(date +%Y%m%d)
        cp $(pwd)/git/.gitconfig ~/.gitconfig

        [ -L ~/.config/nvim ] && rm ~/.config/nvim
        [ -d ~/.config/nvim/ ] && mv ~/.config/nvim ~/.config/nvim$(date +%Y%m%d)
        ln -s $(pwd)/nvim ~/.config/nvim

        [ -L ~/.config/Code/User/settings.json ] && rm ~/.config/Code/User/settings.json
        [ -f ~/.config/Code/User/settings.json ] && mv ~/.config/Code/User/settings.json ~/.config/Code/User/settings$(date +%Y%m%d).json
        ln -s $(pwd)/vscode/settings.json ~/.config/Code/User/settings.json

        [ -L ~/.config/Code\ -\ OSS/User/settings.json ] && rm ~/.config/Code\ -\ OSS/User/settings.json
        [ -f ~/.config/Code\ -\ OSS/User/settings.json ] && mv ~/.config/Code\ -\ OSS/User/settings.json ~/.config/Code\ -\ OSS/User/settings$(date +%Y%m%d).json
        ln -s $(pwd)/vscode/settings.json ~/.config/Code\ -\ OSS/User/settings.json

        [ -L ~/.ideavimrc ] && rm ~/.ideavimrc
        [ -f ~/.ideavimrc ] && mv ~/.ideavimrc ~/.ideavimrc$(date +%Y%m%d)
        ln -s $(pwd)/intellij/.ideavimrc ~/.ideavimrc
        # nvim --headless -c 'Lazy install' -c 'Lazy update' -c 'quitall'
      args:
        chdir: "{{ playbook_dir }}"
