---

- hosts: localhost
  vars:
    gitemail: "mark@[domain]" # avoid bot scraping via a template
  become: yes
  tasks:
    - name: If arch, do this
      include_role:
        name: arch
      when: ansible_os_family == "Archlinux"

    - name: If ubuntu, do this
      include_role:
        name: ubuntu
      when: ansible_os_family == "Debian"

    - name: Set bash/nvim/vscode/idea config
      become: no
      shell: |
        [ -L ~/.bashrc ] && rm ~/.bashrc
        [ -f ~/.bashrc ] && mv ~/.bashrc ~/.bashrc$(date +%Y%m%d)
        ln -s $(pwd)/bash/.bashrc ~/.bashrc

        [ -L ~/.inputrc ] && rm ~/.inputrc
        [ -f ~/.inputrc ] && mv ~/.inputrc ~/.inputrc$(date +%Y%m%d)
        ln -s $(pwd)/bash/.inputrc ~/.inputrc

        [ -L ~/.xprofile ] && rm ~/.xprofile
        [ -f ~/.xprofile ] && mv ~/.xprofile ~/.xprofile$(date +%Y%m%d)
        ln -s $(pwd)/bash/.xprofile ~/.xprofile

        [ -L ~/.gitconfig ] && rm ~/.gitconfig
        [ -f ~/.gitconfig ] && [ ! -f ~/.gitconfig$(date +%Y%m%d) ] && mv ~/.gitconfig ~/.gitconfig$(date +%Y%m%d)
        [ -f ~/.gitconfig ] && rm ~/.gitconfig
        # we copy later using a template to obscure the email address

        [ -L ~/.config/nvim ] && rm ~/.config/nvim
        [ -d ~/.config/nvim/ ] && mv ~/.config/nvim ~/.config/nvim$(date +%Y%m%d)
        ln -s $(pwd)/nvim ~/.config/nvim

        [ -L ~/.config/Code/User/settings.json ] && rm ~/.config/Code/User/settings.json
        [ -f ~/.config/Code/User/settings.json ] && mv ~/.config/Code/User/settings.json ~/.config/Code/User/settings$(date +%Y%m%d).json
        ln -s $(pwd)/vscode/settings.json ~/.config/Code/User/settings.json

        # @MarkFix arch specific...
        [ -L ~/.config/Code\ -\ OSS/User/settings.json ] && rm ~/.config/Code\ -\ OSS/User/settings.json
        [ -f ~/.config/Code\ -\ OSS/User/settings.json ] && mv ~/.config/Code\ -\ OSS/User/settings.json ~/.config/Code\ -\ OSS/User/settings$(date +%Y%m%d).json
        ln -s $(pwd)/vscode/settings.json ~/.config/Code\ -\ OSS/User/settings.json

        [ -L ~/.ideavimrc ] && rm ~/.ideavimrc
        [ -f ~/.ideavimrc ] && mv ~/.ideavimrc ~/.ideavimrc$(date +%Y%m%d)
        ln -s $(pwd)/intellij/.ideavimrc ~/.ideavimrc

        # nvim --headless -c 'Lazy install' -c 'Lazy update' -c 'quitall'
      args:
        chdir: "{{ playbook_dir }}"

    - name: Copy gitconfig template
      become: no
      template:
        src: git/gitconfig.j2
        dest: ~/.gitconfig
