---

- hosts: localhost
  vars:
    gitemail: "mark@[domain]" # avoid bot scraping via a template
  become: yes
  tasks:
    - name: If arch, do this
      include_role:
        name: arch-workstation
      when: ansible_os_family == "Archlinux"

    - name: If ubuntu, do this
      include_role:
        name: ubuntu-workstation
      when: ansible_os_family == "Debian"

    - name: Set bash/nvim/vscode/idea config
      become: no
      changed_when: false
      shell: bash {{ playbook_dir }}/install_workstation_config.sh {{ playbook_dir }}
      args:
        chdir: "{{ playbook_dir }}"

    - name: Copy gitconfig template
      become: no
      changed_when: false
      template:
        src: config_files/gitconfig.j2
        dest: ~/.gitconfig
